<a href="https://colab.research.google.com/github/Poluru-Venkata-Koushik/Data_structures_algorithms_Python/blob/main/LinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In a linear regression model, each variable is said estimated to be a weighted sum of input values and is offset by some constant called bias.


for example,
the variables for a car's success yeild are safety performance 
then `yeild=c1*safety+c2*performance+b1)` b1 is the bias


In [1]:
#1st algorithm. (kinda a crop yeild measurement)
import numpy as np
import torch

In [3]:
# array's representations (temp,rainfall,humidity)            
inputs=np.array([[73,67,43],[91,88,64],[87,134,58],[102,43,37],[69,96,70]],dtype='float32')
inputs

array([[ 73.,  67.,  43.],
       [ 91.,  88.,  64.],
       [ 87., 134.,  58.],
       [102.,  43.,  37.],
       [ 69.,  96.,  70.]], dtype=float32)

In [4]:
Target_yields=np.array([[56,70],[81,101],[119,133],[22,37],[103,119]],dtype='float32')
Target_yields

array([[ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.]], dtype=float32)

In [5]:
#convert them into pytorch tensors
inputs=torch.from_numpy(inputs)
Target_yields=torch.from_numpy(Target_yields)
print(inputs,Target_yields)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]]) tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [6]:
'''
#weights and biases can be expressed as matrix
[
  wt11  wt12  b1
  wt21  wt22  b2
]
'''

'\n#weights and biases can be expressed as matrix\n[\n  wt11  wt12  b1\n  wt21  wt22  b2\n]\n'

In [22]:
#torch.randn creates a tensor with given shape and randomly picks values from normal districbutiondistribution 
w=torch.randn(2,3,requires_grad=True)
b=torch.randn(2,requires_grad=True)
print(w)
print(b)


tensor([[ 1.3593, -0.5934, -0.6924],
        [-0.5372,  0.3190,  0.7824]], requires_grad=True)
tensor([-0.0425,  0.7292], requires_grad=True)
