<a href="https://colab.research.google.com/github/Poluru-Venkata-Koushik/Data_structures_algorithms_Python/blob/main/Linear_regression_mine2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch

In [2]:
inputs=np.array([[73,67,43],[91,88,64],[87,134,58],[102,43,37],[69,96,70]],dtype='float32')
inputs


array([[ 73.,  67.,  43.],
       [ 91.,  88.,  64.],
       [ 87., 134.,  58.],
       [102.,  43.,  37.],
       [ 69.,  96.,  70.]], dtype=float32)

In [3]:
Target_yields=np.array([[56,70],[81,101],[119,133],[22,37],[103,119]],dtype='float32')
Target_yields

array([[ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.]], dtype=float32)

In [4]:
inputs=torch.from_numpy(inputs)
Target_yields=torch.from_numpy(Target_yields)
print(inputs,Target_yields)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]]) tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [5]:
w=torch.randn(2,3,requires_grad=True)
b=torch.randn(2,requires_grad=True)
print(w)
print(b)


tensor([[ 0.0367,  0.4767,  0.9195],
        [ 1.1380,  0.1185, -0.3996]], requires_grad=True)
tensor([0.8482, 0.0139], requires_grad=True)


In [8]:
w.backward

<bound method Tensor.backward of tensor([[ 0.0367,  0.4767,  0.9195],
        [ 1.1380,  0.1185, -0.3996]], requires_grad=True)>

In [12]:
print(w.grad)

None
