<a href="https://colab.research.google.com/github/Poluru-Venkata-Koushik/Data_structures_algorithms_Python/blob/main/LinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In a linear regression model, each variable is said estimated to be a weighted sum of input values and is offset by some constant called bias.


for example,
the variables for a car's success yeild are safety performance 
then `yeild=c1*safety+c2*performance+b1)` b1 is the bias


In [ ]:
#1st algorithm. (kinda a crop yeild measurement)
import numpy as np
import torch

In [ ]:
# array's representations (temp,rainfall,humidity)            
inputs=np.array([[73,67,43],[91,88,64],[87,134,58],[102,43,37],[69,96,70]],dtype='float32')
inputs

array([[ 73.,  67.,  43.],
       [ 91.,  88.,  64.],
       [ 87., 134.,  58.],
       [102.,  43.,  37.],
       [ 69.,  96.,  70.]], dtype=float32)

In [ ]:
Target_yields=np.array([[56,70],[81,101],[119,133],[22,37],[103,119]],dtype='float32')
Target_yields

array([[ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.]], dtype=float32)

In [ ]:
#convert them into pytorch tensors
inputs=torch.from_numpy(inputs)
Target_yields=torch.from_numpy(Target_yields)
print(inputs,Target_yields)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]]) tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [ ]:
'''
#weights and biases can be expressed as matrix
[
  wt11  wt12  b1
  wt21  wt22  b2
]
'''

'\n#weights and biases can be expressed as matrix\n[\n  wt11  wt12  b1\n  wt21  wt22  b2\n]\n'

In [ ]:
#torch.randn creates a tensor with given shape and randomly picks values from normal districbutiondistribution 
w=torch.randn(2,3,requires_grad=True)
b=torch.randn(2,requires_grad=True)
print(w)
print(b)


tensor([[ 1.3593, -0.5934, -0.6924],
        [-0.5372,  0.3190,  0.7824]], requires_grad=True)
tensor([-0.0425,  0.7292], requires_grad=True)


In [ ]:
#https://youtu.be/m_tkL7DufPk?t=2301.Watch to understand if u forget why we do transpose of the matrix


In [ ]:
# inputs*W'+b can be performed by the below function


def predict_fruita_fruitb(inputs):
  return inputs @ w.t()+b # @ performs matrix multiplication and .t() for transpose
predict_fruita_fruitb(inputs)

tensor([[ 29.6601,  16.5313],
        [ 27.1271,  29.9917],
        [ -1.4519,  42.1215],
        [ 87.4769, -11.3991],
        [-11.6800,  49.0571]], grad_fn=<AddBackward0>)

In [ ]:
print(predict_fruita_fruitb(inputs))
print(Target_yields)


tensor([[ 29.6601,  16.5313],
        [ 27.1271,  29.9917],
        [ -1.4519,  42.1215],
        [ 87.4769, -11.3991],
        [-11.6800,  49.0571]], grad_fn=<AddBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [ ]:
print(Target_yields-predict_fruita_fruitb(inputs)) # this is very worse

tensor([[ 26.3399,  53.4687],
        [ 53.8729,  71.0083],
        [120.4519,  90.8785],
        [-65.4769,  48.3991],
        [114.6800,  69.9429]], grad_fn=<SubBackward0>)


In [ ]:
#Loss function (MEAN SQUARED ERROR)MSE

diff=predict_fruita_fruitb(inputs)-Target_yields
diff=diff*diff
average=(torch.sum(diff))/diff.numel() #numel returns the number of elements in array
average #this prints the mean squared error. we square to remove negative polarities if any

tensor(5893.7949, grad_fn=<DivBackward0>)

In [ ]:
#mse function

def mse(pred,target):
  diff=pred-target
  return ((torch.sum(diff*diff))/diff.numel())
loss=mse(predict_fruita_fruitb(inputs),Target_yields)
print(loss)

tensor(5893.7949, grad_fn=<DivBackward0>)


In [ ]:
print(w)
print(w.grad) # prints out derivatives of loss wrt to weights

tensor([[ 1.3593, -0.5934, -0.6924],
        [-0.5372,  0.3190,  0.7824]], requires_grad=True)
tensor([[-3707.7676, -6167.9839, -3434.3296],
        [-5606.8345, -6160.9072, -3760.2822]])


In [ ]:
print(b)
print(b.grad)

tensor([-0.0425,  0.7292], requires_grad=True)
tensor([-49.9736, -66.7395])


In [ ]:
#derivative of loss wrt to weight gives us slope of loss function(rate of change of loss)
# b.grad and w.gard gives us the slopes. postive slope says that if weight is increased, loss increases. and if negative slope is increasing, then loss will decrease 
 

In [ ]:
 with torch.no_grad():
   w-=w.grad * 1e-5
   b-=b.grad * 1e-5 
print(w,b)

tensor([[ 1.4335, -0.4700, -0.6237],
        [-0.4251,  0.4422,  0.8576]], requires_grad=True) tensor([-0.0415,  0.7305], requires_grad=True)


In [ ]:
model_2=predict_fruita_fruitb(inputs)
loss=mse(model_2,Target_yields)
print(loss)

tensor(3470.3855, grad_fn=<DivBackward0>)
