<a href="https://colab.research.google.com/github/Poluru-Venkata-Koushik/Data_structures_algorithms_Python/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [9]:
a=np.array([1,2,3,4])
b=np.array([2,2,2,2])


In [10]:
c=np.dot(a,b)
c

20

In [12]:
(a*b).sum() #does the same as np.dot()

20

In [16]:
#numpy is 100 times faster than performing the same operation using loop


`Multi-dimensional` arrays

In [17]:
# a 3*3 matrix can be represented this way:

np_3by3=np.array([[1,2,3],[4,5,6],[7,8,9]])
np_3by3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
# You can also create n dimensional arrays using numpy

np_3by3by2=np.array([[[1,2],[3,4]],[[5,6],[7,9]],[[10,11],[12,13]]])
np_3by3by2

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  9]],

       [[10, 11],
        [12, 13]]])

In [20]:
np_3by3by2[1][1][1]

9

In [21]:
#.shape is used to find the shape of array


To perform multiplication of two arrays(`Matrix multiplication`).
we can either use `np.matmul()` or simply `@`

In [23]:
a_1=np.array([[1,2,3],[4,5,6],[7,8,9]])
a_2=np.array([[1],[2],[3]])
a12_matmul=np.matmul(a_1,a_2)
a12_matmul

array([[14],
       [32],
       [50]])

In [24]:
a_1*a_2

array([[ 1,  2,  3],
       [ 8, 10, 12],
       [21, 24, 27]])

In [25]:
a12_at= a_1 @ a_2
a12_at

array([[14],
       [32],
       [50]])

Working with `CSV(Comma Seperated Values) data files`

In [ ]:
# a csv file with 10000 readings of (Temperature,rainfall,humidity) is downloaded  

In [27]:
import urllib.request
urllib.request.urlretrieve('https://hub.jovian.ml/wp-content/uploads/2020/08/climate.csv','climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x7fcf3b491f10>)

In [29]:
climate_data=np.genfromtxt('climate.txt',delimiter=',',skip_header=True)

In [31]:
climate_data.shape

(10000, 3)