<a href="https://colab.research.google.com/github/Poluru-Venkata-Koushik/Data_structures_algorithms_Python/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
a=np.array([1,2,3,4])
b=np.array([2,2,2,2])


In [3]:
c=np.dot(a,b)
c

20

In [4]:
(a*b).sum() #does the same as np.dot()

20

In [ ]:
#numpy is 100 times faster than performing the same operation using loop


`Multi-dimensional` arrays

In [6]:
# a 3*3 matrix can be represented this way:

np_3by3=np.array([[1,2,3],[4,5,6],[7,8,9]])
np_3by3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# You can also create n dimensional arrays using numpy

np_3by3by2=np.array([[[1,2],[3,4]],[[5,6],[7,9]],[[10,11],[12,13]]])
np_3by3by2

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  9]],

       [[10, 11],
        [12, 13]]])

In [8]:
np_3by3by2[1][1][1]

9

In [ ]:
#.shape is used to find the shape of array


To perform multiplication of two arrays(`Matrix multiplication`).
we can either use `np.matmul()` or simply `@`

In [9]:
a_1=np.array([[1,2,3],[4,5,6],[7,8,9]])
a_2=np.array([[1],[2],[3]])
a12_matmul=np.matmul(a_1,a_2)
a12_matmul

array([[14],
       [32],
       [50]])

In [10]:
a_1*a_2

array([[ 1,  2,  3],
       [ 8, 10, 12],
       [21, 24, 27]])

In [11]:
a12_at= a_1 @ a_2
a12_at

array([[14],
       [32],
       [50]])

Working with `CSV(Comma Seperated Values) data files`

In [ ]:
# a csv file with 10000 readings of (Temperature,rainfall,humidity) is downloaded  

In [12]:
import urllib.request
urllib.request.urlretrieve('https://hub.jovian.ml/wp-content/uploads/2020/08/climate.csv','climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x7fc8440d9990>)

In [14]:
climate_data=np.genfromtxt('climate.txt',delimiter=',',skip_header=True)

In [15]:
climate_data.shape

(10000, 3)

In [16]:
climate_data


array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [17]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

array([5, 7, 9])

In [18]:
arr1+arr2

array([5, 7, 9])

In [19]:
arr1-arr2

array([-3, -3, -3])

In [20]:
arr1*arr2

array([ 4, 10, 18])

`Broadcasting` : Numpy allows arithmetic operations between two matrices of different shapes



In [21]:
 arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])
 arr3.shape

(3, 3)

In [23]:
arr4=np.array([1,2,3])
arr4.shape

(3,)

In [24]:
arr3+arr4

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [25]:
#basically it takes the matrix with less shape and duplicates it into the same shape of the other. But it works only if the matrix can be replicated in its shape



In [27]:
#numpy arrays also allow comparision operations. The output is array of booleans



In [28]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [29]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
np.random.rand(10)

array([0.66669205, 0.28677028, 0.44554044, 0.80004943, 0.71597717,
       0.10518023, 0.82261173, 0.06532963, 0.18846637, 0.37675678])

In [35]:
np.full([2,3],40)

array([[40, 40, 40],
       [40, 40, 40]])

In [36]:
np.arange(10,90,3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [38]:
np.linspace(10,90,5)

array([10., 30., 50., 70., 90.])