<a href="https://colab.research.google.com/github/Poluru-Venkata-Koushik/Data_structures_algorithms_Python/blob/main/PYTORCH.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [4]:
t1=torch.tensor(1.)
t1

tensor(1.)

In [5]:
t1.dtype

torch.float32

In [7]:
t1=torch.tensor([1.,2,3,4])
t1

tensor([1., 2., 3., 4.])

In [8]:
t1.shape

torch.Size([4])

In [9]:
#It is not possible to create tensors with irregular shapes

Gradient 

In [47]:
x=torch.tensor(3.,requires_grad=True)
w=torch.tensor(4.,requires_grad=True)
b=torch.tensor(5.,requires_grad=True)

In [51]:
y=w*x+b

In [54]:
y

tensor(17., grad_fn=<AddBackward0>)

In [55]:
y.backward()

In [59]:
print(b.grad)

tensor(1.)


Functions

In [60]:
t=torch.full((3,2),42)

In [62]:
t3=torch.full((3,2),54)

In [64]:
torch.cat((t,t3))

tensor([[42, 42],
        [42, 42],
        [42, 42],
        [54, 54],
        [54, 54],
        [54, 54]])

In [65]:
torch.sin(t)

tensor([[-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [67]:
t3.reshape((3,1,2))

tensor([[[54, 54]],

        [[54, 54]],

        [[54, 54]]])

interoperable with numpy pandas ....

In [68]:
import numpy as np

In [73]:
x=np.array(([1.,2],[3,4]))

In [74]:
x

array([[1., 2.],
       [3., 4.]])

In [75]:
torch.from_numpy(x)

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [76]:
#.numy() to return to numpy 

In [77]:
#example 1

In [86]:
inputs=np.array([[73,67,43],[91,88,64],[87,134,58],[102,43,37],[69,96,70.]],dtype="float32")

In [87]:
inputs

array([[ 73.,  67.,  43.],
       [ 91.,  88.,  64.],
       [ 87., 134.,  58.],
       [102.,  43.,  37.],
       [ 69.,  96.,  70.]], dtype=float32)

In [88]:
outputs=np.array([[56,70],[81,101],[119,133],[22,37],[103,119.]],dtype="float32")

In [89]:
outputs.dtype

dtype('float32')

In [90]:
inputs=torch.from_numpy(inputs)
outputs=torch.from_numpy(outputs)

In [109]:
w=torch.randn((2,3),requires_grad=True)
b=torch.randn((2),requires_grad=True)

In [110]:
w

tensor([[-1.2425,  0.3148, -2.4845],
        [-2.0522,  0.6624, -1.0410]], requires_grad=True)

In [111]:
 def model(x):
   return x @ w.t() + b

In [112]:
pred=model(inputs)

In [113]:
print(outputs)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [114]:
def mean_sqaure_error(t1,t2):
  diff=t1-t2
  return torch.sum(diff**2)/diff.numel()

In [126]:
loss=mean_sqaure_error(pred,outputs)
loss

tensor(78826.9844, grad_fn=<DivBackward0>)

In [117]:
loss.backward()

In [118]:
print(w)
print(w.grad)

tensor([[-1.2425,  0.3148, -2.4845],
        [-2.0522,  0.6624, -1.0410]], requires_grad=True)
tensor([[-24394.3730, -26129.8887, -16400.9160],
        [-22438.8613, -23090.3203, -14614.0918]])


In [120]:
print(b)
print(b.grad)

tensor([-1.5754,  0.5349], requires_grad=True)
tensor([-290.8549, -264.5934])


In [121]:
# if slope is increasing (grad is +ve) ==> if w is further increased, loss increases and viceversa
# if slope is decreasing (grad is -ve) ==> if w is further increased, loss decreases and viceversa

In [123]:
with torch.no_grad():# no grad to not track this gradient calc
  w-=w.grad*1e-5
  b-=b.grad*1e-5

In [124]:
loss=mean_sqaure_error(model(inputs),outputs)

In [125]:
print(loss)

tensor(32899.7734, grad_fn=<DivBackward0>)


In [127]:
#set grads to 0 else it will add to new grads

In [129]:
w.grad.zero_()
b.grad.zero_()

tensor([0., 0.])

In [140]:
for i in range(10000): #for 100 epochs
  loss=mean_sqaure_error(model(inputs),outputs)
  loss.backward()
  with torch.no_grad():
    w-=w.grad * 1e-5
    b-=b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [141]:
mean_sqaure_error(model(inputs),outputs)

tensor(0.5147, grad_fn=<DivBackward0>)